export const black = '#000000'
export const darkestGray = '#29292c'
export const darkGray = '#3d3e44'
export const darkPurple = '#282b36'
export const mediumGray = '#9b9aa1'
export const lightGray = '#DBDBDB'
export const lightWarmGray = '#f5f5f5'
export const offWhite = '#b7bdc5'
export const tan = '#fcf8f2'
export const thoughtbotRed = '#ed3e44'
export const transparent = 'rgba(0, 0, 0, 0)'
export const white = '#ffffff'

export const baseText = darkGray
export const darkText = darkestGray
export const background = white
export const border = thoughtbotRed
export const selected = thoughtbotRed
export const unselected = lightGray
